### ISSUE TITLE
can't found some functions 

### ISSUE THREAD

**Issue by smohameds** [ibrahimSmuhammad/mongo_transaction#1]
can't found some function like 
starts_with and ends_with

**Comment by ibrahimSmuhammad** [comment]
Hello, @smohameds 
 Helpers functions don't affect by this package, I think it's your Laravel Version. you may need to check this [doc](https://laravel.com/docs/8.x/helpers#method-starts-with) If you have a version higher than 5.7. because `starts_with` changed to be `Str::startsWith()`.

**Comment by googleshokry** [comment]
Thanks @ibrahimSmuhammad ,
These functions are not available in Laravel 8, I am installing this package to add missing functions
https://github.com/laravel/helpers
